# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-05 15:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_activityroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityroom',
            name='fk_topic_code',
            field=models.CharField(default=datetime.datetime(2016, 5, 5, 10, 53, 48, 420591), max_length=64),
            preserve_default=False,
        ),
    ]
