# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-05 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_activityroom_fk_topic_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='fk_congress',
        ),
    ]
