# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-24 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20160505_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
