# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-26 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_room_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='town',
        ),
        migrations.AddField(
            model_name='room',
            name='fk_section_type_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
