# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-26 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitiestype',
            name='fk_user_modified',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities_type_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
