# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-13 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20160626_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
    ]
