# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-08-13 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.IntegerField(),
        ),
    ]
