# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-01 18:45
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupschedule',
            name='count',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupschedule',
            name='fk_user_assistent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assitent', to=settings.AUTH_USER_MODEL),
        ),
    ]
