# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-02 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20160502_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicagenda',
            old_name='fk_topic_code',
            new_name='fk_room_topic_code',
        ),
    ]
