# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-05 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_agenda_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicagenda',
            old_name='fk_room_topic_code',
            new_name='fk_activity_room_code',
        ),
    ]
