# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-27 00:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_auto_20160505_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupschedule',
            name='fk_user_assistent',
        ),
        migrations.AddField(
            model_name='signupschedule',
            name='fk_sign_up_code',
            field=models.CharField(default=datetime.datetime(2016, 5, 27, 0, 50, 47, 729613, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
    ]
