# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-31 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0008_capacityroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupschedule',
            name='count',
        ),
    ]
