# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-31 23:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_remove_signupschedule_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacityroom',
            name='fk_user_created',
        ),
        migrations.AddField(
            model_name='signupschedule',
            name='count',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='capacityRoom',
        ),
    ]
