# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-01 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0015_auto_20160601_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupschedule',
            name='count',
            field=models.CharField(max_length=2000),
        ),
    ]
