# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-07-03 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_activityroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='fk_user_professor',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='profesor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
